### ISSUE TITLE
Randomly getting 'An existing connection was forcibly closed by the remote host' error

### ISSUE THREAD

**Issue by jmevel** [thomasarmel/socket-server-mocker#6]
I implemented a code very similar to the [SMTP Mock example](https://github.com/thomasarmel/socket-server-mocker/blob/master/tests/smtp_mock.rs).
Some times my test is passing but most of the times I get 

> thread 'email_client::tests::test_smtp_mock' panicked at 'Could not send email: lettre::transport::smtp::Error { kind: Network, source: Os { code: 10054, kind: ConnectionReset, message: "An existing connection was forcibly closed by the remote host." } }'

In my CI, on Ubuntu, same issue but with a different message

> thread 'email_client::tests::test_smtp_mock' panicked at 'Could not send email: lettre::transport::smtp::Error { kind: Network, source: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" } }'

Have you ever encountered this problem? 
The thing is from time to time it actually works...

Thank you

**Comment by thomasarmel** [comment]
Hi,
Yes actually I met some issues with SMTP that I was not able to reproduce all the time. But as I remember it was not an issue of connection closing, but the wrong message was sent.
The unique solution I found was to trigger pipeline again.
I you find the reason I would be interested :)

**Comment by jmevel** [comment]
I just added a `println!("{}", String::from_utf8(email.formatted()).unwrap());` in my code and was able to capture both a success and failing ones.

Success :

>running 1 test
From: whitney_aut <lucas@example.org>
Reply-To: jonathon_explicabo <madalyn@example.org>
To: lillie_aperiam <maxine@example.com>
Subject: libero.
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 7bit
Date: Sat, 01 Apr 2023 08:34:23 +0000

repellendus dolorem quis in.
Email sent successfully!
test email_client::tests::test_smtp_mock ... ok

Failure :

>running 1 test
From: annetta_architecto <toby@example.org>
Reply-To: eleanore_ipsum <alicia@example.com>
To: zoe_distinctio <alexander@example.com>
Subject: accusamus.
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 7bit
Date: Sat, 01 Apr 2023 08:35:39 +0000
>
>est quas ducimus maiores et molestias.
thread 'email_client::tests::test_smtp_mock' panicked at 'Could not send email: lettre::transport::smtp::Error { kind: Network, source: Os { code: 10054, kind: ConnectionReset, message: "An existing connection was forcibly closed by the remote host." } }', src\email_client.rs:60:23
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\panicking.rs:575
   1: core::panicking::panic_fmt
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\core\src\panicking.rs:64
   2: zero2prod::email_client::EmailClient::send_email
             at .\src\email_client.rs:60
   3: zero2prod::email_client::tests::test_smtp_mock
             at .\src\email_client.rs:119
   4: zero2prod::email_client::tests::test_smtp_mock::closure$0
             at .\src\email_client.rs:84
   5: core::ops::function::FnOnce::call_once<zero2prod::email_client::tests::test_smtp_mock::closure_env$0,tuple$<> >
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483\library\core\src\ops\function.rs:507
   6: core::ops::function::FnOnce::call_once
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\core\src\ops\function.rs:507
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test email_client::tests::test_smtp_mock ... FAILED
>
>failures:
>
>failures:
    email_client::tests::test_smtp_mock
    
I'm generating a random text body of only one paragraph use the `fake` crate.

I don't see any useful information when running with `RUST_BACKTRACE=full` but maybe you've better eyes than me:

>0:     0x7ff7bc873622 - std::backtrace_rs::backtrace::dbghelp::trace
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
   1:     0x7ff7bc873622 - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff7bc873622 - std::sys_common::backtrace::_print_fmt
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\sys_common\backtrace.rs:65
   3:     0x7ff7bc873622 - std::sys_common::backtrace::_print::impl$0::fmt
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\sys_common\backtrace.rs:44
   4:     0x7ff7bc8931eb - core::fmt::write
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\core\src\fmt\mod.rs:1208
   5:     0x7ff7bc86b97a - std::io::Write::write_fmt<alloc::vec::Vec<u8,alloc::alloc::Global> >
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\io\mod.rs:1682
   6:     0x7ff7bc87336b - std::sys_common::backtrace::_print
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\sys_common\backtrace.rs:47
   7:     0x7ff7bc87336b - std::sys_common::backtrace::print
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\sys_common\backtrace.rs:34
   8:     0x7ff7bc876499 - std::panicking::default_hook::closure$1
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\panicking.rs:267
   9:     0x7ff7bc8760a3 - std::panicking::default_hook
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\panicking.rs:283
  10:     0x7ff7bc543478 - alloc::boxed::impl$47::call
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\alloc\src\boxed.rs:2032
  11:     0x7ff7bc543478 - test::test_main::closure$0
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\test\src\lib.rs:135
  12:     0x7ff7bc876d60 - alloc::boxed::impl$47::call
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\alloc\src\boxed.rs:2032
  13:     0x7ff7bc876d60 - std::panicking::rust_panic_with_hook
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\panicking.rs:692
  14:     0x7ff7bc876abe - std::panicking::begin_panic_handler::closure$0
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\panicking.rs:579
  15:     0x7ff7bc87431f - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\sys_common\backtrace.rs:137
  16:     0x7ff7bc876770 - std::panicking::begin_panic_handler
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\panicking.rs:575
  17:     0x7ff7bc947d35 - core::panicking::panic_fmt
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\core\src\panicking.rs:64
  18:     0x7ff7bc4e23fc - zero2prod::email_client::EmailClient::send_email
                               at C:\Users\jerome\Desktop\Computer stuff\Rust\zero2prod\src\email_client.rs:60
  19:     0x7ff7bc4e035d - zero2prod::email_client::tests::test_smtp_mock
                               at C:\Users\jerome\Desktop\Computer stuff\Rust\zero2prod\src\email_client.rs:119
  20:     0x7ff7bc4d2188 - zero2prod::email_client::tests::test_smtp_mock::closure$0
                               at C:\Users\jerome\Desktop\Computer stuff\Rust\zero2prod\src\email_client.rs:84
  21:     0x7ff7bc4da852 - core::ops::function::FnOnce::call_once<zero2prod::email_client::tests::test_smtp_mock::closure_env$0,tuple$<> >
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483\library\core\src\ops\function.rs:507
  22:     0x7ff7bc54a42f - core::ops::function::FnOnce::call_once
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\core\src\ops\function.rs:507
  23:     0x7ff7bc54a42f - test::__rust_begin_short_backtrace<enum2$<core::result::Result<tuple$<>,alloc::string::String> >,enum2$<core::result::Result<tuple$<>,alloc::string::String> > (*)()>
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\test\src\lib.rs:657
  24:     0x7ff7bc512530 - test::run_test::closure$1
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\test\src\lib.rs:648
  25:     0x7ff7bc512530 - core::ops::function::FnOnce::call_once<test::run_test::closure_env$1,tuple$<> >
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\core\src\ops\function.rs:507
  26:     0x7ff7bc548c8d - alloc::boxed::impl$45::call_once
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\alloc\src\boxed.rs:2000
  27:     0x7ff7bc548c8d - core::panic::unwind_safe::impl$23::call_once
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\core\src\panic\unwind_safe.rs:271
  28:     0x7ff7bc548c8d - std::panicking::try::do_call
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\panicking.rs:483
  29:     0x7ff7bc548c8d - std::panicking::try
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\panicking.rs:447
  30:     0x7ff7bc548c8d - std::panic::catch_unwind
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\panic.rs:137
  31:     0x7ff7bc548c8d - test::run_test_in_process
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\test\src\lib.rs:680
  32:     0x7ff7bc548c8d - test::run_test::run_test_inner::closure$0
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\test\src\lib.rs:574
  33:     0x7ff7bc50980a - test::run_test::run_test_inner::closure$1
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\test\src\lib.rs:601
  34:     0x7ff7bc50980a - std::sys_common::backtrace::__rust_begin_short_backtrace<test::run_test::run_test_inner::closure_env$1,tuple$<> >
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\sys_common\backtrace.rs:121
  35:     0x7ff7bc51280b - std::thread::impl$0::spawn_unchecked_::closure$1::closure$0
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\thread\mod.rs:550
  36:     0x7ff7bc51280b - core::panic::unwind_safe::impl$23::call_once
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\core\src\panic\unwind_safe.rs:271
  37:     0x7ff7bc51280b - std::panicking::try::do_call
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\panicking.rs:483
  38:     0x7ff7bc51280b - std::panicking::try
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\panicking.rs:447
  39:     0x7ff7bc51280b - std::panic::catch_unwind
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\panic.rs:137
  40:     0x7ff7bc51280b - std::thread::impl$0::spawn_unchecked_::closure$1
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\thread\mod.rs:549
  41:     0x7ff7bc51280b - core::ops::function::FnOnce::call_once<std::thread::impl$0::spawn_unchecked_::closure_env$1<test::run_test::run_test_inner::closure_env$1,tuple$<> >,tuple$<> >
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\core\src\ops\function.rs:507
  42:     0x7ff7bc8821ac - alloc::boxed::impl$45::call_once
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\alloc\src\boxed.rs:2000
  43:     0x7ff7bc8821ac - alloc::boxed::impl$45::call_once
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\alloc\src\boxed.rs:2000
  44:     0x7ff7bc8821ac - std::sys::windows::thread::impl$0::new::thread_start
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\sys\windows\thread.rs:56
  45:     0x7ffcdf8926bd - BaseThreadInitThunk
  46:     0x7ffce1aca9f8 - RtlUserThreadStart
  
  It doesn't seem related to the port being already open because if I try with any other random port it also fails on the first try

**Comment by jmevel** [comment]
I deleted my previous comment because I just realized the `panic` was coming from my code...
However there's still an issue with the mock server.

I added some logs. 
First are the logs from the email before sending it and then what the mock server received using the `pop_received_message` function.

Success:

> running 1 test
From: adalberto_itaque <milford@example.net>
Reply-To: velma_at <opal@example.com>
To: bernie_eveniet <eliseo@example.org>
Subject: temporibus.
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 7bit
Date: Sat, 01 Apr 2023 09:01:50 +0000
>
>est quaerat consequuntur error aut.
Email sent successfully!
>
>Messages received by server:
EHLO DESKTOP-2Q06VQ1
>
>MAIL FROM:<milford@example.net>
>
>RCPT TO:<eliseo@example.org>
>
>DATA
>
>From: adalberto_itaque <milford@example.net>
Reply-To: velma_at <opal@example.com>
To: bernie_eveniet <eliseo@example.org>
Subject: temporibus.
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 7bit
Date: Sat, 01 Apr 2023 09:01:50 +0000
>
>est quaerat consequuntur error aut.
test email_client::tests::test_smtp_mock ... ok

Failure:

>running 1 test
From: retta_eum <charles@example.com>
Reply-To: stephania_enim <maurice@example.net>
To: martin_molestiae <elise@example.com>
Subject: cupiditate.
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 7bit
Date: Sat, 01 Apr 2023 09:03:15 +0000
>
>saepe quam libero iste numquam cum necessitatibus animi enim.
Could not send email: lettre::transport::smtp::Error { kind: Network, source: Os { code: 10054, kind: ConnectionReset, message: "An existing connection was forcibly closed by the remote host." } }
>
>Messages received by server:
EHLO DESKTOP-2Q06VQ1
>
>failures:
>
>failures:
    email_client::tests::test_smtp_mock
    
 As you can see, the server closed the connection after the very first message `EHLO [name of my computer]`

**Comment by thomasarmel** [comment]
Ok quite strange. Can I see your code please?

**Comment by jmevel** [comment]
Yes sure, I'm not sure I'll have more free time this weekend but Monday I'll try to share you a minimal code to reproduce the problem.

**Comment by jmevel** [comment]
Hi @thomasarmel !

Here is [a repository](https://github.com/jmevel/smtp-test) you can clone it and test it with the `test_smtp_mock` test function in the `email_client.rs` file.

So far I could never get this sample code to work. Always getting error `10054` on Windows and `104` on Linux. 

I honestly don't know what am I doing wrong.
Thanks for having a look at it!

**Comment by thomasarmel** [comment]
Just to verify: what happen in case you set **0** as SMTP port (let the OS choose a free port)? And then specify the choosen port using _listening_port()_ method.

Maybe the problem comes from the fact that you have port 2525 opened twice?

I'll have a further look on it

**Comment by jmevel** [comment]
Hi @thomasarmel 

It's been a while I didn't have the time to do some Rust programming. 
Now I'm back to it and in the meantime I also completely switched to Linux.

This time, running [your SMTP mock test](https://github.com/thomasarmel/socket-server-mocker/blob/master/tests/smtp_mock.rs#L7C5-L7C5) and also running [my SMTP mock test](https://github.com/jmevel/smtp-test/blob/master/src/email_client.rs#L46) both yield to the same error

>lettre::transport::smtp::Error { kind: Network, source: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" } }

Have you ever encountered this error message? Do you still maintain this project?

**Comment by jmevel** [comment]
Hi @thomasarmel, I finally had time to go back to this issue and I found the root cause however I really can't explain it, it seems very weird to me !

In your [SMTP Mock example](https://github.com/thomasarmel/socket-server-mocker/blob/master/tests/smtp_mock.rs) try inverting the initialization of `email_builder` and `mailer`.

So instead of 

```rust
// Create a client based on a SmtpTransport
let email_builder = Message::builder()
    .from(
        "Alice Dupont <alice.dupont@localhost.mock>"
            .parse()
            .unwrap(),
    )
    .reply_to(
        "Alice Dupont <alice.dupont@localhost.mock>"
            .parse()
            .unwrap(),
    )
    .to("Bob Dupond <bob.dupond@localhost.mock>".parse().unwrap())
    .subject("Happy new year")
    .body(String::from("Be happy!"))
    .unwrap();

// Mail client opens a remote connection on mocked SMTP server
let mailer = SmtpTransport::relay("127.0.0.1")
    .unwrap()
    .tls(Tls::None)
    .port(2525)
    .timeout(Some(std::time::Duration::from_secs(1)))
    .build();
// Send the email
mailer.send(&email_builder).unwrap();
```

You have

```rust
// Mail client opens a remote connection on mocked SMTP server
let mailer = SmtpTransport::relay("127.0.0.1")
    .unwrap()
    .tls(Tls::None)
    .port(2525)
    .timeout(Some(std::time::Duration::from_secs(1)))
    .build();

// Create a client based on a SmtpTransport
let email_builder = Message::builder()
    .from(
        "Alice Dupont <alice.dupont@localhost.mock>"
            .parse()
            .unwrap(),
    )
    .reply_to(
        "Alice Dupont <alice.dupont@localhost.mock>"
            .parse()
            .unwrap(),
    )
    .to("Bob Dupond <bob.dupond@localhost.mock>".parse().unwrap())
    .subject("Happy new year")
    .body(String::from("Be happy!"))
    .unwrap();

// Send the email
mailer.send(&email_builder).unwrap();
```

And now you get the same issue as me !
>thread 'test_smtp_mock' panicked at 'called `Result::unwrap()` on an `Err` value: lettre::transport::smtp::Error { kind: Network, source: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" } }

And since last time I even completely migrated to Linux so this is not a Windows-only issue.

How could you explain this weird behavior? In my opinion it should not matter at all in which order we are instantiating our variables, it should work in both ways.

**Comment by jmevel** [comment]
Hi @thomasarmel, I finally had time to go back to this issue and I found the root cause however I really can't explain it, it seems very weird to me !

In your [SMTP Mock example](https://github.com/thomasarmel/socket-server-mocker/blob/master/tests/smtp_mock.rs) try inverting the initialization of `email_builder` and `mailer`.

So instead of 

```rust
// Create a client based on a SmtpTransport
let email_builder = Message::builder()
    .from(
        "Alice Dupont <alice.dupont@localhost.mock>"
            .parse()
            .unwrap(),
    )
    .reply_to(
        "Alice Dupont <alice.dupont@localhost.mock>"
            .parse()
            .unwrap(),
    )
    .to("Bob Dupond <bob.dupond@localhost.mock>".parse().unwrap())
    .subject("Happy new year")
    .body(String::from("Be happy!"))
    .unwrap();

// Mail client opens a remote connection on mocked SMTP server
let mailer = SmtpTransport::relay("127.0.0.1")
    .unwrap()
    .tls(Tls::None)
    .port(2525)
    .timeout(Some(std::time::Duration::from_secs(1)))
    .build();
// Send the email
mailer.send(&email_builder).unwrap();
```

You have

```rust
// Mail client opens a remote connection on mocked SMTP server
let mailer = SmtpTransport::relay("127.0.0.1")
    .unwrap()
    .tls(Tls::None)
    .port(2525)
    .timeout(Some(std::time::Duration::from_secs(1)))
    .build();

// Create a client based on a SmtpTransport
let email_builder = Message::builder()
    .from(
        "Alice Dupont <alice.dupont@localhost.mock>"
            .parse()
            .unwrap(),
    )
    .reply_to(
        "Alice Dupont <alice.dupont@localhost.mock>"
            .parse()
            .unwrap(),
    )
    .to("Bob Dupond <bob.dupond@localhost.mock>".parse().unwrap())
    .subject("Happy new year")
    .body(String::from("Be happy!"))
    .unwrap();

// Send the email
mailer.send(&email_builder).unwrap();
```

And now you get the same issue as me !
>thread 'test_smtp_mock' panicked at 'called `Result::unwrap()` on an `Err` value: lettre::transport::smtp::Error { kind: Network, source: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" } }

And since last time I even completely migrated to Linux so this is not a Windows-only issue.

How could you explain this weird behavior? In my opinion it should not matter at all in which order we are instantiating our variables, it should work in both ways.

**Comment by jmevel** [comment]
You're right, I thought it was failing 100% of the times but it's actually working once in a while on my side.

Thanks for taking the time to investigate this issue. 
I hope I will be able to use your crate at some point and improve my code coverage 😉

**Comment by thomasarmel** [comment]
@jmevel it looks like now the problem occurs less often, could you please check?

**Comment by jmevel** [comment]
> @jmevel it looks like now the problem occurs less often, could you please check?

Hi thomas, thanks for the new 0.0.5 version and the follow up on this issue.

I upgraded lettre & socket-server-mocker on my [sample SMTP project](https://github.com/jmevel/smtp-test) however I still get the same issue as before every single time I execute my test.

> lettre::transport::smtp::Error { kind: Network, source: Os { code: 10054, kind: ConnectionReset, message: "Une connexion existante a dû être fermée par l’hôte distant." } } 

I'm on my work computer on Windows right now. Havent had time to test on Linux yet.
